const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY'
const SET_PARENT_CATEGORY_SELECTED = 'SET_PARENT_CATEGORY_SELECTED'
const SET_CHILD_CATEGORY_SELECTED = 'SET_CHILD_CATEGORY_SELECTED'
const GET_ALL_SOUNDS = 'GET_ALL_SOUNDS'
const AUTHORIZE_REQUEST = 'AUTHORIZE_REQUEST'
const AUTHORIZE_CHECK_LOCALSTORAGE = 'AUTHORIZE_CHECK_LOCALSTORAGE'
const AUTHORIZE_LOGOUT_CLEAR_LOCALSTORAGE = 'AUTHORIZE_LOGOUT_CLEAR_LOCALSTORAGE'
const BUY_RINGTONE_REQUEST = 'BUY_RINGTONE_REQUEST'
const SEARCH_REQUEST = 'SEARCH_REQUEST'
const SEARCH_RESULT_CLEAN = 'SEARCH_RESULT_CLEAN'
const PLAYER_STARTED_PLAY_WITH_ID = 'PLAYER_STARTED_PLAY_WITH_ID'
const PLAYER_STOPED_PLAY = 'PLAYER_STOPED_PLAY'


export {
    GET_ALL_CATEGORY,
    SET_PARENT_CATEGORY_SELECTED,
    GET_ALL_SOUNDS,
    SET_CHILD_CATEGORY_SELECTED,
    AUTHORIZE_REQUEST,
    AUTHORIZE_CHECK_LOCALSTORAGE,
    AUTHORIZE_LOGOUT_CLEAR_LOCALSTORAGE,
    BUY_RINGTONE_REQUEST,
    SEARCH_REQUEST,
    SEARCH_RESULT_CLEAN,
    PLAYER_STARTED_PLAY_WITH_ID,
    PLAYER_STOPED_PLAY
  };